- Dockerfile
- README.md
- langextract/__init__.py
- pyproject.toml
Fixes the "failed to find libmagic" error by bundling pre-built libmagic libraries via `pylibmagic>=0.5.0`.
- Add `pylibmagic>=0.5.0` dependency for bundled libraries
- Add `[full]` install option and pre-import handling
- Update README with troubleshooting and Docker sections
- Bump version to 1.0.1
Fixes #6
> Fix: Resolve libmagic ImportError (#6)

- docs/examples/medication_examples.md
This PR updates the code example in `docs/examples/medication_examples.md` to clarify how the `output_dir` parameter affects where the output file is saved when using `lx.io.save_annotated_documents`.
- Explicitly sets `output_dir="."` in the example to ensure the file is saved in the current working directory.
- Adds comments and a note explaining that the default value of `output_dir` is `test_output/`, which may not match user expectations.
The previous example could confuse users, as it implied that setting `output_name` alone controls the full file path. In practice, the file is saved to the `test_output/` directory by default. This clarification improves usability and prevents unnecessary debugging.
Fixes #8 
☑️ I have signed the Google CLA.
> docs: clarify output_dir behavior in medication_examples.md

- README.md
- docs/examples/longer_text_example.md
- docs/examples/medication_examples.md
This PR ensures consistent file saving behavior across all documentation examples by adding `output_dir="."` to all `save_annotated_documents` calls.
Without explicitly setting `output_dir`, files are saved to `test_output/` by default, which can confuse users who expect files to be saved in their current directory.
Added `output_dir="."` parameter to all `save_annotated_documents` calls in:
- README.md
- docs/examples/longer_text_example.md  
- docs/examples/medication_examples.md (first occurrence)
This follows the same pattern that was applied to one instance in medication_examples.md previously.
All examples have been verified to include the parameter. Users will now find their output files in their current working directory as expected.
> docs: add output_dir="." to all save_annotated_documents examples

- exceptions.py
- langextract/__init__.py
- langextract/annotation.py
- langextract/chunking.py
- langextract/exceptions.py
- langextract/inference.py
- langextract/io.py
- langextract/prompting.py
- langextract/resolver.py
- langextract/tokenizer.py
Introduces a common base exception class (`LangExtractError`) that all library-specific exceptions inherit from. This enables users to catch all LangExtract errors with a single except clause, improving error handling ergonomics.
Previously, users had no way to catch all library-specific exceptions with a single handler. This change provides a consistent exception hierarchy that follows Python best practices for library design.
Fixes #21
Choose one: Code health
Executed the existing test suite with formatting and linting checks:
```
$ ./autoformat.sh
$ tox -e py311
$ mypy langextract tests --ignore-missing-imports
```
All 156 tests pass with no new mypy errors introduced.
- …
> Add LangExtractError base exception for centralized error handling

- langextract/io.py
This PR fixes a bug where `save_annotated_documents` fails when passing a string path (e.g., `output_dir="."`) as shown in the README example. The function was expecting a `pathlib.Path` object but the type hint and README example suggest strings should be supported.
The fix updates the function to:
- Accept both `pathlib.Path` and `str` types for the `output_dir` parameter
- Convert string paths to `Path` objects before calling `.mkdir()`
- Maintain backward compatibility with existing code using `Path` objects
This ensures users following the README Quick Start example won't encounter:
```
AttributeError: 'str' object has no attribute 'mkdir'
```
Choose one: **Bug fix**
Tested the fix with multiple scenarios to ensure both string and Path objects work correctly.
-   [x] I have read and …
> Fix save_annotated_documents to handle string paths

- .github/workflows/validate_pr_template.yaml
Add GitHub Actions workflow to validate PR template usage. Ensures required sections are present and placeholder text is replaced.
Fixes # (No issue created - straightforward workflow addition)
Code health
- Validated YAML syntax and workflow logic
- Will test with follow-up PR
> Add PR template validation workflow

- langextract/inference.py
- tests/inference_test.py
Fix parameter mismatch in OllamaLanguageModel constructor that caused TypeError when using Ollama with langextract. The `extract()` function passes `model_id` but `OllamaLanguageModel.__init__()` expected `model`, preventing Ollama integration from working.
Fixes #27
Bug fix
```bash
$ python -m pytest tests/inference_test.py::TestOllamaLanguageModel -v
```
The existing unit test was updated to use the new parameter name and continues to pass, verifying the fix works correctly.
> fix: Change OllamaLanguageModel parameter from 'model' to 'model_id'

- .github/workflows/ci.yaml
- .github/workflows/validate_pr_template.yaml
- README.md
- examples/ollama/.dockerignore
- examples/ollama/Dockerfile
- examples/ollama/README.md
- examples/ollama/docker-compose.yml
- examples/ollama/quickstart.py
- tests/test_ollama_integration.py
- tox.ini
Add Ollama integration support with Docker examples and documentation for LangExtract. This PR introduces a complete example setup for using Ollama with LangExtract, including containerized deployment options and automated testing.
Fixes #7
Fixes #22
Fixes #56
Type: Feature
- `examples/ollama/` directory with:
- Docker configuration (`Dockerfile`, `.dockerignore`, `docker-compose.yml`)
- Quickstart Python example (`quickstart.py`)
- Documentation (`README.md`)
- `tests/test_ollama_integration.py` - Integration test for Ollama functionality
- `.github/workflows/ci.yaml` - Updated CI pipeline to include Ollama tests
- `.github/workflows/validate_pr_template.yaml` - PR template validation updates
- `README.md` - Added Ollama integration documentation
- `tox.ini` - Added Ollama test …
> feat: Add Ollama integration with Docker examples and CI tests

- .github/workflows/check-infrastructure-changes.yml
- .github/workflows/check-linked-issue.yml
- .github/workflows/check-pr-size.yml
- .github/workflows/validate_pr_template.yaml
Adds workflow_dispatch trigger to validation workflows to enable manual triggering via GitHub UI or CLI.
- Added `workflow_dispatch:` trigger to:
- check-linked-issue.yml
- check-pr-size.yml  
- validate_pr_template.yaml
- Added conditional logic to ensure PR-specific steps only run on PR events
- Prevents errors when manually triggering workflows that expect PR context
- Allows maintainers to manually trigger workflows for testing
- Useful for debugging workflow issues
- Can manually re-run checks on PRs when needed
After merging, workflows can be manually triggered via:
- GitHub UI: Actions tab → Select workflow → Run workflow
- CLI: `gh workflow run <workflow-file.yml> --ref <branch>`
Fixes #0 (Infrastructure improvement - maintainer-initiated)
> Add manual trigger capability to validation workflows

- .github/workflows/ci.yaml
- langextract/providers/__init__.py
- pyproject.toml
- tests/provider_plugin_test.py
- tox.ini
Adds comprehensive test coverage for the provider plugin system introduced in #97.
Related to #99, #111
Feature (Testing)
- Smoke tests for plugin discovery, registration, and usage flows
- Edge case handling (malformed plugins, import errors)  
- Plugin priority override validation
- Environment variable controls (`LANGEXTRACT_DISABLE_PLUGINS`)
- E2E test simulating pip-installed plugin lifecycle
- CI/CD integration with new tox environments
```bash
pytest tests/provider_plugin_test.py -v
tox -e plugin-smoke
tox -e plugin-integration
```
> Add comprehensive tests for provider plugin system

- langextract/__init__.py
- tests/extract_precedence_test.py
- tests/init_test.py
Adds `config` and `model` to `extract()` while maintaining full backward compatibility.
* Added two new settings to `extract()`:
- `config`: An optional `ModelConfig`.
- `model`: An optional `BaseModel` implementation.
* Parameter precedence in `extract()` for model selection is as follows (from
chosen first to last):
- `model`
- `config`
- `model_id` (with `api_key`, `temperature` and `model_url`)
- `language_model_type` (deprecated.)
* Dropped unused `constraints` from `extract()`
Fixes #106 
All tests succeed with:
```
$ poetry run pytest tests/
```
-   [X] I have read and acknowledged Google's Open Source [Code of conduct](https://opensource.google/conduct).
-   [X] I have read the [Contributing](https://github.com/google-health/langextract/blob/master/CONTRIBUTING.md) page, and I …
> Adding model and config parameters to extract()

- README.md
- examples/custom_provider_plugin/README.md
- examples/custom_provider_plugin/langextract_provider_example/provider.py
- examples/custom_provider_plugin/langextract_provider_example/schema.py
- examples/custom_provider_plugin/test_example_provider.py
- langextract/__init__.py
- langextract/factory.py
- langextract/inference.py
- langextract/providers/README.md
- langextract/providers/gemini.py
- langextract/providers/ollama.py
- langextract/providers/schemas/__init__.py
- langextract/providers/schemas/gemini.py
- langextract/resolver.py
- langextract/schema.py
- pyproject.toml
- tests/extract_precedence_test.py
- tests/extract_schema_integration_test.py
- tests/factory_schema_test.py
- tests/init_test.py
- tests/progress_test.py
- tests/provider_plugin_test.py
- tests/provider_schema_test.py
- tests/registry_test.py
- tests/schema_test.py
- tests/visualization_test.py
Refactors the schema constraint system to enable provider-specific implementations through a plugin architecture. Each LLM provider can now define its own optimal approach for structured output generation while maintaining backward compatibility.
Related to #128, #59, #99
Feature
```
$ pytest tests/extract_schema_integration_test.py -v
$ pytest tests/factory_schema_test.py -v
$ pytest tests/provider_schema_test.py -v
$ tox -e live-api
$ tox -e ollama-integration
```
Verified backward compatibility with existing providers and tested schema generation with multiple providers.
[Contributing](https://github.com/google-health/langextract/blob/master/CONTRIBUTIN …
> Refactor schema system to support provider-specific constraints

- pyproject.toml
Bump version to 1.0.6 for new release.
- Added support for Hugging Face style model IDs in Ollama provider
- Updated Ollama quickstart example to use ModelConfig pattern
- Fixed test infrastructure for provider registry
> Release v1.0.6

- langextract/inference.py
- langextract/providers/gemini.py
- langextract/providers/ollama.py
- langextract/providers/openai.py
- tests/inference_test.py
- tests/test_live_api.py
Updates kwargs handling across all provider models to properly merge stored and runtime parameters. Runtime kwargs take precedence over initialization kwargs, allowing dynamic configuration overrides.
Fixes #136
Bug fix
All tests pass including live API and Ollama integration tests:
```
$ pytest tests/inference_test.py -v
$ tox -e format
$ tox -e lint-src,lint-tests
$ tox -e live-api
$ tox -e ollama-integration
```
[Individual CLA](https://cla.developers.google.com/about/google-individual)
or am covered by my company's
[Corporate …
> Update kwargs handling for provider models

- langextract/__init__.py
- langextract/debug_utils.py
- langextract/inference.py
- langextract/tokenizer.py
Enables debug logging when `debug=True` is passed to `extract()`. Logs function calls, arguments, returns, and timing with automatic redaction of sensitive keys (`api_key`, `token`, etc.).
Key improvements:
- Library-safe: No global side effects, respects host logging
- Secure: Auto-redacts sensitive parameters and nested dicts
- Correct: Uses `inspect.signature` for proper function/method detection
- Performant: Early exit guards when debugging disabled
**For better issue support**: Debug logs from non-sensitive test data can be shared in GitHub issues to help diagnose problems.
Fixes #127
Related to #4, #132, #63, #139 - Helps debug parsing errors and encoding issues
Feature
```
$ pytest tests -v
$ tox -e format
$ tox -e lint-src,lint-tests
```
-   [x] I have read and acknowledged …
> Add debug logging when debug=True in lx.extract()

- examples/ollama/README.md
- examples/ollama/quickstart.py
- langextract/providers/ollama.py
- tests/inference_test.py
Increases default timeout for Ollama from 30s to 120s to support slower models. Adds explicit timeout parameter that can be configured via constructor or passed through lx.extract().
This change resolves timeout issues when using Ollama with large models or long contexts.
Fixes #152
Addresses #85 (timeout errors with long context)
Related to #136 (kwargs not being passed through properly)
Bug fix
```
$ python -m pytest tests/inference_test.py::TestOllamaLanguageModel -xvs
$ ./autoformat.sh
```
[Individual …
> Expose timeout parameter for Ollama provider

- langextract/extraction.py
- langextract/io.py
- tests/data_lib_test.py
Fix URL detection to prevent unintended fetching of text that starts with URLs. Add `fetch_urls` keyword-only parameter for explicit control.
Fixes #177
Bug fix
```bash
pytest tests/data_lib_test.py::IsUrlTest -v  # 3 new URL validation tests
pytest tests -m "not live_api" -q  # 273 tests passing
./autoformat.sh langextract/extraction.py langextract/io.py tests/data_lib_test.py  # Passing
```
[Individual CLA](https://cla.developers.google.com/about/google-individual)
or am covered by my company's
[Corporate …
> Fix URL detection to prevent unintended fetching

- COMMUNITY_PROVIDERS.md
Adding AWS Bedrock community provider information to the plugin registry.
[Related to #148](https://github.com/google/langextract/issues/148
)
Documentation
N/A
[Individual CLA](https://cla.developers.google.com/about/google-individual)
or am covered by my company's
[Corporate CLA](https://cla.developers.google.com/about/google-corporate).
-   [x] I have discussed my proposed solution with code owners in the linked
issue(s) and we have agreed upon the general approach.
-   [x] I have made any needed documentation changes, or noted …
> feat: Add AWS Bedrock community provider to the plugin registry

- .pylintrc
- langextract/data.py
- langextract/tokenizer.py
Configures pylint to accept descriptive TypeVar names like TLanguageModel.
Related to #190
Code health
```bash
tox -e format  # Pass
tox -e lint-src  # Pass
pytest tests -m "not live_api" -q  # 273 passed
```
[Individual CLA](https://cla.developers.google.com/about/google-individual)
or am covered by my company's
[Corporate CLA](https://cla.developers.google.com/about/google-corporate).
-   [x] I have discussed my proposed solution with code owners in the linked
issue(s) and we have agreed upon the general approach.
-   [x] I have …
> fix: Allow T-prefixed TypeVars in pylint config

- langextract/annotation.py
- langextract/extraction.py
- tests/init_test.py
Adds `show_progress` parameter to control progress bar visibility independently of debug logging. Users can now show/hide progress without affecting debug output.
Fixes #221
Choose one: Bug fix
```bash
./autoformat.sh
pylint --rcfile=.pylintrc langextract
pylint --rcfile=tests/.pylintrc tests
pytest tests/init_test.py -k "test_show_progress" -v
```
All 4 parameterized test cases verify progress bar control works correctly.
-   [x] I have read and acknowledged Google's Open Source [Code of conduct](https://opensource.google/conduct).
-   [x] I have read the [Contributing](https://github.com/google-health/langextract/blob/master/CONTRIBUTING.md) page, and I either signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual) or am covered by my company's …
> feat: Add show_progress parameter for independent progress bar control

- .github/ISSUE_TEMPLATE/config.yml
This pull request fixes a broken link in the issue creation template (`.github/ISSUE_TEMPLATE/config.yml`). The "Community Support" contact link was pointing to `https://github.com/google-health/langextract/discussions`, which resulted in a 404 error for users trying to access the discussions page.
The link has been corrected to point to the correct discussions URL for the repository: `https://github.com/google/langextract/discussions`. Please note that this link will still result in a 404 error until the repository's "Discussions" tab is enabled by a maintainer.
Fixes #220
(Bug fix)
I verified the fix by manually navigating to the corrected URL on a different repository (`https://github.com/google/mangle/discussions`) to ensure it leads to the correct page.
Since this is a simple URL …
> docs: Fix broken community support link in issue template

- .github/workflows/ci.yaml
Fetch exact commit SHA instead of branch HEAD to prevent race conditions.
> Internal: Strengthen CI/CD security for fork PR validation
